"use client";

import { useState } from "react";
import { ArrowRight, CheckCircle2, ChevronRight, CircleUserRound, Menu, Search, Sparkles, X } from "lucide-react";

type Skill = { name: string; category: string; description: string; price: string; tone: "yellow" | "pink" | "silver"; owned?: boolean; delivery: string };
type Props = {
  skills: Skill[];
  filtered: Skill[];
  category: string;
  query: string;
  setCategory: (value: string) => void;
  setQuery: (value: string) => void;
  setSelectedSkill: (value: Skill) => void;
};

const categories = ["Tất cả", "Hình ảnh", "Video", "Biên tập video"];
const goals = [
  { title: "Ảnh quảng cáo & thương hiệu", copy: "Poster sản phẩm, ảnh thương hiệu và bộ concept nhất quán.", category: "Hình ảnh", mark: "01" },
  { title: "Video bán hàng / KOC AI", copy: "Video review, UGC, quảng cáo ngắn và các format viral.", category: "Video", mark: "02" },
  { title: "Xây kênh & Content", copy: "Tìm ngách, kịch bản và quy trình phát triển nội dung.", category: "Biên tập video", mark: "03" },
  { title: "Bắt đầu với AI", copy: "Bộ Skill đơn giản để làm nhanh, có hướng dẫn từng bước.", category: "Tất cả", mark: "04" },
];

export default function Marketplace({ skills, filtered, category, query, setCategory, setQuery, setSelectedSkill }: Props) {
  const [menuOpen, setMenuOpen] = useState(false);
  const chooseGoal = (value: string) => {
    setCategory(value);
    document.querySelector("#thu-vien")?.scrollIntoView({ behavior: "smooth" });
  };

  return <main className="min-h-screen bg-[#f8f6ee] text-[#171717]">
    <div className="overflow-hidden bg-[#171717] py-2 text-xs font-black uppercase tracking-[.16em] text-[#d8ff32]"><div className="animate-[pulse_3s_ease-in-out_infinite] whitespace-nowrap text-center">⚡ Thanh toán xong — nhận link ngay · Cập nhật Skill miễn phí · Hỗ trợ chọn đúng công cụ</div></div>
    <header className="sticky top-0 z-30 border-b border-black/10 bg-[#f8f6ee]/95 backdrop-blur"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 lg:px-8"><a href="#top" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#171717] text-xl font-black text-[#d8ff32]">S</span><span className="text-2xl font-black tracking-[-.08em]">skill<span className="text-[#b08c00]">lab</span></span></a><nav className="hidden items-center gap-7 text-sm font-bold text-black/60 md:flex"><a href="#muc-tieu">Theo nhu cầu</a><a href="#thu-vien">Danh mục Skill</a><a href="#cam-ket">Cam kết</a><a href="#don-hang">Đơn hàng của tôi</a></nav><div className="hidden md:block"><a href="/admin" className="inline-flex items-center gap-2 rounded-xl bg-[#171717] px-4 py-3 text-sm font-black text-white"><CircleUserRound size={17} /> Quản trị</a></div><button aria-label="Mở menu" onClick={() => setMenuOpen(!menuOpen)} className="rounded-lg p-2 md:hidden">{menuOpen ? <X /> : <Menu />}</button></div>{menuOpen && <nav className="border-t border-black/10 bg-white px-5 py-4 text-sm font-bold md:hidden"><div className="flex flex-col gap-4"><a href="#muc-tieu">Theo nhu cầu</a><a href="#thu-vien">Danh mục Skill</a><a href="#don-hang">Đơn hàng</a><a href="/admin">Quản trị</a></div></nav>}</header>
    <section id="top" className="border-b border-black/10 bg-[radial-gradient(circle_at_78%_25%,rgba(216,255,50,.55),transparent_22%),radial-gradient(circle_at_12%_68%,rgba(0,0,0,.08),transparent_24%)]"><div className="mx-auto grid max-w-7xl gap-12 px-5 py-20 lg:grid-cols-[1.1fr_.9fr] lg:px-8 lg:py-28"><div><p className="inline-flex items-center gap-2 rounded-full bg-[#171717] px-4 py-2 text-xs font-black uppercase tracking-[.16em] text-[#d8ff32]"><Sparkles size={14} /> Nền tảng Skill AI thực chiến</p><h1 className="mt-7 max-w-3xl text-[clamp(3.3rem,7vw,6.4rem)] font-black leading-[.88] tracking-[-.1em]">Kho Skill AI<br /><span className="text-[#a88300]">làm được việc.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-black/60">Chọn Skill, prompt và quy trình đúng nhu cầu. Mua một lần, nhận tài nguyên dùng ngay trong công việc.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#muc-tieu" className="inline-flex items-center gap-2 rounded-xl bg-[#171717] px-6 py-4 font-black text-white">Khám phá theo nhu cầu <ArrowRight size={18} /></a><a href="#thu-vien" className="rounded-xl border border-black/15 bg-white px-6 py-4 font-black">Xem tất cả Skill</a></div><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-xs font-black uppercase tracking-[.08em] text-black/50"><span>✓ Mua một lần</span><span>✓ Nhận link ngay</span><span>✓ Cập nhật miễn phí</span></div></div><div className="relative rounded-[32px] bg-[#171717] p-5 text-white shadow-2xl"><div className="absolute right-5 top-5 rounded-full bg-[#d8ff32] px-3 py-1 text-[10px] font-black uppercase tracking-widest text-black">SkillLab / Store</div><div className="min-h-[360px] rounded-[24px] border border-white/10 bg-[linear-gradient(145deg,#282828,#080808)] p-7"><p className="text-xs font-black uppercase tracking-[.18em] text-[#d8ff32]">Hôm nay bạn cần làm gì?</p><p className="mt-16 max-w-sm text-5xl font-black leading-[.9] tracking-[-.08em]">Biến AI thành<br /><span className="text-[#d8ff32]">kết quả thật.</span></p><div className="mt-12 grid grid-cols-3 gap-3"><div className="h-14 rounded-2xl bg-[#d8ff32]" /><div className="h-14 rounded-2xl bg-white/15" /><div className="h-14 rounded-2xl bg-white/15" /></div></div></div></div></section>
    <section id="muc-tieu" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><p className="text-xs font-black uppercase tracking-[.18em] text-[#a88300]">Chọn theo mục tiêu</p><div className="mt-3 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><h2 className="text-5xl font-black tracking-[-.09em]">Bạn đang cần<br />làm gì?</h2><p className="mt-4 max-w-xl text-black/55">Chọn một mục tiêu, SkillLab sẽ lọc sẵn nhóm Skill phù hợp để chị bắt đầu nhanh hơn.</p></div><p className="text-sm font-bold text-black/45">{skills.length} Skill đang sẵn sàng</p></div><div className="mt-10 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{goals.map((goal) => <button key={goal.mark} onClick={() => chooseGoal(goal.category)} className="group rounded-3xl border border-black/10 bg-white p-6 text-left transition hover:-translate-y-1 hover:border-[#171717] hover:bg-[#d8ff32]"><span className="text-xs font-black text-black/40">{goal.mark}</span><h3 className="mt-12 text-2xl font-black leading-none tracking-[-.06em]">{goal.title}</h3><p className="mt-4 text-sm leading-6 text-black/55">{goal.copy}</p><span className="mt-7 inline-flex items-center gap-1 text-sm font-black">Xem Skill <ChevronRight size={16} /></span></button>)}</div></section>
    <section id="thu-vien" className="border-y border-black/10 bg-[#171717] px-5 py-20 text-white"><div className="mx-auto max-w-7xl"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[.18em] text-[#d8ff32]">Kho Skill</p><h2 className="mt-3 text-5xl font-black tracking-[-.09em]">Chọn công cụ,<br />bắt tay làm ngay.</h2></div><div className="relative w-full max-w-sm"><Search size={17} className="absolute left-4 top-1/2 -translate-y-1/2 text-white/40" /><input aria-label="Tìm Skill" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Tìm Skill, prompt, quy trình..." className="w-full rounded-xl border border-white/15 bg-white/10 py-3.5 pl-11 pr-4 text-sm outline-none focus:border-[#d8ff32]" /></div></div><div className="mt-8 flex gap-3 overflow-auto pb-2">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`whitespace-nowrap rounded-full px-5 py-2.5 text-sm font-black ${category === item ? "bg-[#d8ff32] text-black" : "border border-white/15 text-white/65"}`}>{item}</button>)}</div><div className="mt-8 grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{filtered.map((skill) => <article key={skill.name} className="rounded-3xl bg-[#f8f6ee] p-4 text-[#171717]"><div className={`relative min-h-44 overflow-hidden rounded-2xl p-5 ${skill.tone === "yellow" ? "bg-[#d8ff32]" : skill.tone === "pink" ? "bg-[#d8ff32]" : "bg-[#d9d9d3]"}`}><div className="absolute -right-8 -top-10 h-40 w-40 rounded-full border-[18px] border-black/15" /><span className="relative rounded-full bg-[#171717] px-3 py-1 text-[10px] font-black uppercase text-white">{skill.category}</span><h3 className="relative mt-12 max-w-[240px] text-3xl font-black leading-none tracking-[-.07em]">{skill.name}</h3></div><div className="px-1 pb-1 pt-5"><p className="min-h-12 text-sm leading-6 text-black/55">{skill.description}</p><div className="mt-5 flex items-center justify-between border-t border-black/10 pt-4"><span className="font-black text-[#927200]">{skill.owned ? "Đã sở hữu" : skill.price}</span><button onClick={() => setSelectedSkill(skill)} className="inline-flex items-center gap-1 text-sm font-black">Xem chi tiết <ChevronRight size={16} /></button></div></div></article>)}</div>{filtered.length === 0 && <p className="mt-8 rounded-2xl border border-dashed border-white/20 p-8 text-center text-white/60">Chưa có Skill phù hợp với từ khóa này.</p>}</div></section>
    <section id="cam-ket" className="mx-auto max-w-7xl px-5 py-20 lg:px-8"><p className="text-xs font-black uppercase tracking-[.18em] text-[#a88300]">Mua một lần, dùng lâu dài</p><div className="mt-4 grid gap-5 md:grid-cols-3"><Benefit title="Nhận link ngay sau thanh toán" copy="Khi hệ thống thanh toán được kết nối, link Skill sẽ mở tự động sau khi đơn được xác nhận." /><Benefit title="Cập nhật phiên bản miễn phí" copy="Mỗi Skill có thể được bổ sung phiên bản và tài nguyên mới trong quá trình vận hành." /><Benefit title="Hỗ trợ chọn đúng Skill" copy="Cần đúng công cụ cho một công việc cụ thể? SkillLab sẽ hướng dẫn lộ trình phù hợp." /></div></section>
    <footer id="don-hang" className="bg-[#171717] px-5 py-14 text-white"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-8 md:flex-row"><div><p className="text-2xl font-black tracking-[-.08em]">skill<span className="text-[#d8ff32]">lab</span></p><p className="mt-3 max-w-sm text-sm leading-6 text-white/50">Kho Skill thực chiến, xây để AI trở thành một phần hữu ích trong công việc hằng ngày.</p></div><div className="text-sm text-white/50"><p className="font-black text-white">Đơn hàng của tôi</p><p className="mt-3">Tra cứu đơn hàng và nhận lại tài nguyên sẽ mở khi phần thanh toán được kết nối.</p></div></div></footer>
  </main>;
}

function Benefit({ title, copy }: { title: string; copy: string }) { return <article className="rounded-3xl border border-black/10 bg-white p-7"><CheckCircle2 className="text-[#a88300]" /><h3 className="mt-12 text-2xl font-black tracking-[-.06em]">{title}</h3><p className="mt-3 leading-7 text-black/55">{copy}</p></article>; }
